import type { Lang } from "./i18n/public-context";

export interface Country {
  code: string;
  name: string;
  nameZh: string;
  hasRegions: boolean;
  /** Default UI language shown when this country is selected. */
  lang: Lang;
  /** Which region-filter widget to render for this country. */
  regionType: "cn-cascade" | "hk-cascade" | "free-text";
}

export const COUNTRIES: Country[] = [
  { code: "CN", name: "China", nameZh: "中国", hasRegions: true, lang: "zh", regionType: "cn-cascade" },
  { code: "US", name: "United States", nameZh: "美国", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "JP", name: "Japan", nameZh: "日本", hasRegions: false, lang: "ja", regionType: "free-text" },
  { code: "KR", name: "South Korea", nameZh: "韩国", hasRegions: false, lang: "ko", regionType: "free-text" },
  { code: "GB", name: "United Kingdom", nameZh: "英国", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "FR", name: "France", nameZh: "法国", hasRegions: false, lang: "fr", regionType: "free-text" },
  { code: "DE", name: "Germany", nameZh: "德国", hasRegions: false, lang: "de", regionType: "free-text" },
  { code: "CA", name: "Canada", nameZh: "加拿大", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "AU", name: "Australia", nameZh: "澳大利亚", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "IT", name: "Italy", nameZh: "意大利", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "ES", name: "Spain", nameZh: "西班牙", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "RU", name: "Russia", nameZh: "俄罗斯", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "BR", name: "Brazil", nameZh: "巴西", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "IN", name: "India", nameZh: "印度", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "MX", name: "Mexico", nameZh: "墨西哥", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "SG", name: "Singapore", nameZh: "新加坡", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "MY", name: "Malaysia", nameZh: "马来西亚", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "TH", name: "Thailand", nameZh: "泰国", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "VN", name: "Vietnam", nameZh: "越南", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "PH", name: "Philippines", nameZh: "菲律宾", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "ID", name: "Indonesia", nameZh: "印度尼西亚", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "NZ", name: "New Zealand", nameZh: "新西兰", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "NL", name: "Netherlands", nameZh: "荷兰", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "BE", name: "Belgium", nameZh: "比利时", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "CH", name: "Switzerland", nameZh: "瑞士", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "SE", name: "Sweden", nameZh: "瑞典", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "NO", name: "Norway", nameZh: "挪威", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "DK", name: "Denmark", nameZh: "丹麦", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "FI", name: "Finland", nameZh: "芬兰", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "PT", name: "Portugal", nameZh: "葡萄牙", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "GR", name: "Greece", nameZh: "希腊", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "AT", name: "Austria", nameZh: "奥地利", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "IE", name: "Ireland", nameZh: "爱尔兰", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "PL", name: "Poland", nameZh: "波兰", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "CZ", name: "Czech Republic", nameZh: "捷克", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "HU", name: "Hungary", nameZh: "匈牙利", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "RO", name: "Romania", nameZh: "罗马尼亚", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "UA", name: "Ukraine", nameZh: "乌克兰", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "TR", name: "Turkey", nameZh: "土耳其", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "SA", name: "Saudi Arabia", nameZh: "沙特阿拉伯", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "AE", name: "United Arab Emirates", nameZh: "阿联酋", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "IL", name: "Israel", nameZh: "以色列", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "EG", name: "Egypt", nameZh: "埃及", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "ZA", name: "South Africa", nameZh: "南非", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "NG", name: "Nigeria", nameZh: "尼日利亚", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "KE", name: "Kenya", nameZh: "肯尼亚", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "AR", name: "Argentina", nameZh: "阿根廷", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "CL", name: "Chile", nameZh: "智利", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "CO", name: "Colombia", nameZh: "哥伦比亚", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "PE", name: "Peru", nameZh: "秘鲁", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "TW", name: "Taiwan", nameZh: "台湾", hasRegions: true, lang: "zh-Hant", regionType: "cn-cascade" },
  { code: "HK", name: "Hong Kong", nameZh: "香港", hasRegions: true, lang: "zh-Hant", regionType: "hk-cascade" },
  { code: "MO", name: "Macau", nameZh: "澳门", hasRegions: true, lang: "zh-Hant", regionType: "cn-cascade" },
  { code: "MM", name: "Myanmar", nameZh: "缅甸", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "KH", name: "Cambodia", nameZh: "柬埔寨", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "LA", name: "Laos", nameZh: "老挝", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "BD", name: "Bangladesh", nameZh: "孟加拉国", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "PK", name: "Pakistan", nameZh: "巴基斯坦", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "LK", name: "Sri Lanka", nameZh: "斯里兰卡", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "NP", name: "Nepal", nameZh: "尼泊尔", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "MN", name: "Mongolia", nameZh: "蒙古", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "KP", name: "North Korea", nameZh: "朝鲜", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "IR", name: "Iran", nameZh: "伊朗", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "IQ", name: "Iraq", nameZh: "伊拉克", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "AF", name: "Afghanistan", nameZh: "阿富汗", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "KZ", name: "Kazakhstan", nameZh: "哈萨克斯坦", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "UZ", name: "Uzbekistan", nameZh: "乌兹别克斯坦", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "MA", name: "Morocco", nameZh: "摩洛哥", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "DZ", name: "Algeria", nameZh: "阿尔及利亚", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "TN", name: "Tunisia", nameZh: "突尼斯", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "LY", name: "Libya", nameZh: "利比亚", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "SD", name: "Sudan", nameZh: "苏丹", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "ET", name: "Ethiopia", nameZh: "埃塞俄比亚", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "TZ", name: "Tanzania", nameZh: "坦桑尼亚", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "GH", name: "Ghana", nameZh: "加纳", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "AO", name: "Angola", nameZh: "安哥拉", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "VE", name: "Venezuela", nameZh: "委内瑞拉", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "CU", name: "Cuba", nameZh: "古巴", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "EC", name: "Ecuador", nameZh: "厄瓜多尔", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "BO", name: "Bolivia", nameZh: "玻利维亚", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "PY", name: "Paraguay", nameZh: "巴拉圭", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "UY", name: "Uruguay", nameZh: "乌拉圭", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "CR", name: "Costa Rica", nameZh: "哥斯达黎加", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "PA", name: "Panama", nameZh: "巴拿马", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "IS", name: "Iceland", nameZh: "冰岛", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "LU", name: "Luxembourg", nameZh: "卢森堡", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "MT", name: "Malta", nameZh: "马耳他", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "CY", name: "Cyprus", nameZh: "塞浦路斯", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "BG", name: "Bulgaria", nameZh: "保加利亚", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "HR", name: "Croatia", nameZh: "克罗地亚", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "RS", name: "Serbia", nameZh: "塞尔维亚", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "SK", name: "Slovakia", nameZh: "斯洛伐克", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "SI", name: "Slovenia", nameZh: "斯洛文尼亚", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "LT", name: "Lithuania", nameZh: "立陶宛", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "LV", name: "Latvia", nameZh: "拉脱维亚", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "EE", name: "Estonia", nameZh: "爱沙尼亚", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "QA", name: "Qatar", nameZh: "卡塔尔", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "KW", name: "Kuwait", nameZh: "科威特", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "BH", name: "Bahrain", nameZh: "巴林", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "OM", name: "Oman", nameZh: "阿曼", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "JO", name: "Jordan", nameZh: "约旦", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "LB", name: "Lebanon", nameZh: "黎巴嫩", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "YE", name: "Yemen", nameZh: "也门", hasRegions: false, lang: "en", regionType: "free-text" },
  { code: "SY", name: "Syria", nameZh: "叙利亚", hasRegions: false, lang: "en", regionType: "free-text" },
];

export const COUNTRY_MAP: Record<string, Country> = {};
for (const c of COUNTRIES) COUNTRY_MAP[c.code] = c;

export const DEFAULT_COUNTRY = "CN";
